# Answer Key

This answer key contains a copy of each exercise text as well as the solutions, but you will not be able to run solution cells here. Copy each solution from this answer key into the main notebook for this learning module and run the code there. 

<div class="alert alert-info"> 

## Exercise 1: Create a NumPy Array from Scratch and Access Its Attributes

Create a 2-dimensional 32-bit integer array called ```myArr2d``` with 4 rows and 3 columns.
</div>

In [16]:
# add your code here
myArr2d = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9],
                    [10,11,12]],
                   dtype='int32')
myArr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

<div class="alert alert-info"> 

Programmatically show the following attributes of ```myArr2d```:
- its shape
- how many total data values there are
- its data type
- the total number of bytes it consumes
</div>

In [17]:
# add your code here
print(myArr2d.shape)
print(myArr2d.size)
print(myArr2d.dtype)
print(myArr2d.nbytes)

(4, 3)
12
int32
48


<div class="alert alert-info"> 

If we had assigned the int8 data type to ```myArr2d``` instead of int32 would we have received an overflow error? Why or why not? In other words, can all the values in ```myArr2d``` be properly represented by an int8 data type?

</div>

Type your answer here: No we would not have received an overflow error because all the values of myArr2D are within the range of data type int8 (-128 to 127).

<div class="alert alert-info"> 

## Exercise 2: Basic Indexing and Slicing

In your ```arr_3d``` make the following selections using indexing and slicing. Note that slicing is never jagged so your data selection for part (d) will include two data values that you cannot see in the image.

<table><tr>
<td> <img src="images/numpy3D_selection1.png" alt="schematic of what to select" width="300"/> </td>
<td> <img src="images/numpy3D_selection2.png" alt="schematic of what to select" width="300"/> </td>
<td> <img src="images/numpy3D_selection3.png" alt="schematic of what to select" width="300"/> </td>
<td> <img src="images/numpy3D_selection4.png" alt="schematic of what to select" width="300"/> </td>
</tr></table

</div>



<div class="alert alert-info"> 

**part (a)**
</div>


In [36]:
# add your code here
arr_3d[1,1,0]

9

<div class="alert alert-info"> 

**part (b)**
</div>

In [37]:
# add your code here
arr_3d[0:2,1,0] 

array([4, 9])

<div class="alert alert-info"> 

**part (c)**
</div>

In [38]:
# add your code here
arr_3d[1:,1:,0]

array([[9, 7],
       [3, 0]])

<div class="alert alert-info"> 

**part (d)**
</div>

In [39]:
# add your code here
arr_3d[:,1:,:]

array([[[ 4,  3],
        [ 7,  4]],

       [[ 9, 10],
        [ 7,  5]],

       [[ 3, 11],
        [ 0,  2]]])

<div class="alert alert-info"> 

## Exercise 3: Advanced Indexing

Using advanced indexing, select the diagonal values (1,7,13,19,25) of the array ```arr```.
</div>

In [59]:
arr = np.array([[1,2,3,4,5],
               [6,7,8,9,10],
               [11,12,13,14,15],
               [16,17,18,19,20],
               [21,22,23,24,25]])

# add your code here
indexes = np.array([0,1,2,3,4])
arr[indexes,indexes]

array([ 1,  7, 13, 19, 25])

<div class="alert alert-info"> 

Now, select the same diagonal values using all negative indexes.
</div>

In [60]:
# add your code here
indexes = np.array([-5,-4,-3,-2,-1])
arr[indexes,indexes]

array([ 1,  7, 13, 19, 25])

<div class="alert alert-info"> 
    
Last, use a conditional statement to generate a boolean array that will select only the even numbers from ```arr```. Hint: Look back to the Python Language Basics lesson if you need to. You'll want the operator that gives you the remainder of division.
</div>

In [61]:
# add your code here
arr[arr % 2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

<div class="alert alert-info"> 

## Exercise 4: Elementwise Operations and Upcasting

Show the data type of ```arr_2d```.

In [76]:
# add your code here

arr_2d.dtype

dtype('int16')

<div class="alert alert-info"> 
    
If you multiply every element of ```arr_2d``` by 2.0, what do you expect the resulting data type to be and why?
</div>

Type your answer: 

I expect the resulting data type to be float64. The 2.0 will be assigned type float64 due to my computer's 64-bit operating system. When I multiply the int16 data values in arr_2d by a float64 data value, the result will be upcast to the data type that consumes the larger amount of memory, which is float64.

<div class="alert alert-info"> 
    
Multiply every element of ```arr_2d``` by 2.0 and save the result as a new variable called ```result```. Show the values in your ```result``` array.

</div>

In [77]:
# add your code here
result = arr_2d * 2.0
result

array([[ 2.,  4.,  6.,  8., 10.],
       [12., 14., 16., 18., 20.]])

<div class="alert alert-info"> 

Show the data type of your array ```result```.
</div>

In [78]:
# add your code here
result.dtype

dtype('float64')

<div class="alert alert-info"> 

## Exercise 5: Broadcasting Practice

The array called ```data``` below contains data that needs to be multiplied by a set of scaling factors. A different scale factor should be applied to each column of the ```data``` array. 

Create a 1D array called ```scale_columns``` containing the pretend scale factors. Your ```scale_columns``` array can contain any values you want, but you will have to decide how many values it should contain to properly broadcast with the ```data``` array as described above. Then, do elementwise multiplication with the arrays using broadcasting to apply the scaling factors to the data.

</div>

In [96]:
data = np.array([[10.2, 9.6, 12.3, 2.7, 5.5],
                 [21.3, 3.9, 8.4, 16.3, 1.1],
                 [17.6, 23.2, 20.1, 5.7, 19.4]])

# add your code here

scale_columns = np.array([1,2,3,4,5])

data * scale_columns

array([[10.2, 19.2, 36.9, 10.8, 27.5],
       [21.3,  7.8, 25.2, 65.2,  5.5],
       [17.6, 46.4, 60.3, 22.8, 97. ]])

<div class="alert alert-info"> 

What if we wanted to apply a different scaling factor to each row instead of each column of the ```data``` array? 

Create a new array called ```scale_rows``` with the appropriate dimensions to broadcast a different scale factor to each row of the ```data``` array (hint: you'll need a singleton dimension). Multiply the arrays together to apply the scaling factors to the data using broadcasting. 

</div>

In [97]:
# add your code here

scale_rows = np.array([[1],[2],[3]])
# OR
# scale_rows = np.array([1,2,3])[:,np.newaxis]

print(scale_rows.shape)

data * scale_rows

(3, 1)


array([[10.2,  9.6, 12.3,  2.7,  5.5],
       [42.6,  7.8, 16.8, 32.6,  2.2],
       [52.8, 69.6, 60.3, 17.1, 58.2]])

<div class="alert alert-info"> 

## Exercise 6: Summary Functions

Use the NumPy API Reference Manual pages for **[np.median()](https://numpy.org/doc/stable/reference/generated/numpy.median.html#numpy.median)**, **[np.min()](https://numpy.org/doc/2.1/reference/generated/numpy.min.html#numpy.min)**, **[np.max()](https://numpy.org/doc/2.1/reference/generated/numpy.max.html#numpy.max)**, **[np.ptp()](https://numpy.org/doc/2.1/reference/generated/numpy.ptp.html#numpy.ptp)** if needed to help you complete the exercise.

Use ```arr_2d```, ```arr_3d```, and the functions linked above to execute the following tasks:

A) Find the median value of ```arr_2d```.
</div>

In [109]:
# add your code here

np.median(arr_2d)

5.5

<div class="alert alert-info"> 

B) Find the minimum data value in each row of ```arr_2d```.
</div>

In [110]:
np.min(arr_2d,axis=1)

array([1, 6], dtype=int16)

<div class="alert alert-info"> 

C) Find the data range (max minus min) of ```arr_2d``` using ```np.ptp()```.
</div>

In [111]:
np.ptp(arr_2d)

9

<div class="alert alert-info"> 

D) Find the data range of each column of ```arr_2d``` using ```np.ptp()```.
</div>

In [112]:
np.ptp(arr_2d,axis=0)

array([5, 5, 5, 5, 5], dtype=int16)

<div class="alert alert-info"> 

E) Find the maximum data value in each time (axis 0) of ```arr_3d```.
</div>

In [113]:
np.max(arr_3d,axis=(1,2))

array([ 7, 10, 11])

<div class="alert alert-info"> 

## Exercise 7: Mathmatical Functions

Use the NumPy API Reference Manual pages for **[np.sin()](https://numpy.org/doc/2.1/reference/generated/numpy.sin.html#numpy.sin)**, **[np.floor()](https://numpy.org/doc/2.1/reference/generated/numpy.floor.html#numpy.floor)**, **[np.round()](https://numpy.org/doc/2.1/reference/generated/numpy.round.html#numpy.round)** to help you complete the following tasks.

A) Calculate the trigonometric sine of the ```degrees``` array. Hint: you'll see in the documentation for ```np.sin()``` that the inputs need to be in radians.
</div>

In [120]:
degrees = np.array([0,45,90,135,180])

# add your code here
np.sin(np.radians(degrees))

array([0.00000000e+00, 7.07106781e-01, 1.00000000e+00, 7.07106781e-01,
       1.22464680e-16])

<div class="alert alert-info"> 

B) Calculate the floor of each value in the ```data_2d``` array.
</div>

In [121]:
data_2d = np.array([[2.16936,0.46812],[100.37213,6.21455]])

# add your code here
np.floor(data_2d)

array([[  2.,   0.],
       [100.,   6.]])

<div class="alert alert-info"> 

C) Round each value in the ```data_2d``` array to 2 decimal places.

In [122]:
data_2d = np.array([[2.16936,0.46812],[100.37213,6.21455]])

# add your code here
np.round(data_2d,decimals=2)

array([[  2.17,   0.47],
       [100.37,   6.21]])

<div class="alert alert-info"> 

## Exercise 8: Array Creation Functions

Use the NumPy array creation functions described in this section to complete the following tasks.

A) Create a 2D array with 5 rows and 4 columns where all the data values are -9999.0.

</div>

In [135]:
# add your code here

np.full((5,4),-9999.0)

array([[-9999., -9999., -9999., -9999.],
       [-9999., -9999., -9999., -9999.],
       [-9999., -9999., -9999., -9999.],
       [-9999., -9999., -9999., -9999.],
       [-9999., -9999., -9999., -9999.]])

<div class="alert alert-info"> 

B) Create a 1D array of northern hemisphere latitudes with 1/4 degree spatial resolution starting at 30.0 degrees and ending at 60.0 degrees. 
</div>

In [136]:
# add your code here

np.linspace(30,60,121)

array([30.  , 30.25, 30.5 , 30.75, 31.  , 31.25, 31.5 , 31.75, 32.  ,
       32.25, 32.5 , 32.75, 33.  , 33.25, 33.5 , 33.75, 34.  , 34.25,
       34.5 , 34.75, 35.  , 35.25, 35.5 , 35.75, 36.  , 36.25, 36.5 ,
       36.75, 37.  , 37.25, 37.5 , 37.75, 38.  , 38.25, 38.5 , 38.75,
       39.  , 39.25, 39.5 , 39.75, 40.  , 40.25, 40.5 , 40.75, 41.  ,
       41.25, 41.5 , 41.75, 42.  , 42.25, 42.5 , 42.75, 43.  , 43.25,
       43.5 , 43.75, 44.  , 44.25, 44.5 , 44.75, 45.  , 45.25, 45.5 ,
       45.75, 46.  , 46.25, 46.5 , 46.75, 47.  , 47.25, 47.5 , 47.75,
       48.  , 48.25, 48.5 , 48.75, 49.  , 49.25, 49.5 , 49.75, 50.  ,
       50.25, 50.5 , 50.75, 51.  , 51.25, 51.5 , 51.75, 52.  , 52.25,
       52.5 , 52.75, 53.  , 53.25, 53.5 , 53.75, 54.  , 54.25, 54.5 ,
       54.75, 55.  , 55.25, 55.5 , 55.75, 56.  , 56.25, 56.5 , 56.75,
       57.  , 57.25, 57.5 , 57.75, 58.  , 58.25, 58.5 , 58.75, 59.  ,
       59.25, 59.5 , 59.75, 60.  ])

<div class="alert alert-info"> 

C) Create a random number generator and use it to create an array with 5 rows and 3 columns filled with random integer values from 1 to 100.
</div>

In [137]:
# add your code here

np.random.default_rng().integers(1,100,(5,3))

array([[59, 73, 42],
       [62, 37, 64],
       [94, 86, 23],
       [10, 79, 43],
       [ 1,  3, 47]], dtype=int64)

<div class="alert alert-info"> 

## Exercise 9: np.sort() and np.argsort()

A) Sort the Denver row of the ```t_mon``` array.
</div>

In [149]:
# add your code here

np.sort(t_mon[1,:])

array([32.5 , 32.87, 33.24, 44.52, 45.64, 52.6 , 60.35, 63.07, 67.25,
       77.38, 80.6 , 86.79])

<div class="alert alert-info"> 

    
B) Sort all rows of the ```t_mon``` array by ascending station elevation.
</div>

In [150]:
# add your code here

sorted_elev = np.argsort(station_elev)
t_mon[sorted_elev]

array([[39.49, 44.85, 49.8 , 56.81, 65.21, 74.73, 80.95, 75.09, 69.36,
        60.9 , 50.33, 47.4 ],
       [32.69, 37.63, 47.02, 52.47, 66.94, 77.12, 78.1 , 77.97, 68.91,
        56.97, 46.16, 35.59],
       [47.39, 53.2 , 52.34, 60.93, 60.49, 66.8 , 68.82, 67.85, 65.02,
        57.91, 52.14, 49.91],
       [25.85, 29.41, 40.77, 48.34, 61.48, 71.98, 80.74, 73.79, 68.32,
        53.36, 39.11, 31.58],
       [57.68, 61.94, 65.26, 65.59, 74.52, 74.31, 75.95, 77.25, 77.32,
        68.11, 63.24, 59.42],
       [51.87, 57.8 , 65.26, 73.61, 80.79, 86.59, 88.84, 89.54, 81.14,
        75.56, 65.68, 54.3 ],
       [21.18, 24.31, 37.95, 50.16, 61.2 , 72.38, 76.71, 76.  , 65.36,
        54.25, 39.67, 30.56],
       [37.13, 43.  , 52.34, 61.52, 72.23, 77.02, 83.13, 78.9 , 74.37,
        62.47, 52.82, 38.8 ],
       [39.02, 46.58, 53.02, 67.46, 77.7 , 87.05, 91.73, 86.88, 78.14,
        68.03, 52.94, 42.55],
       [32.87, 33.24, 44.52, 52.6 , 63.07, 77.38, 86.79, 80.6 , 67.25,
        60.35, 45.64

<div class="alert alert-info"> 
    
C) Sort all rows of the ```t_mon``` array by descending station elevation. Hint: Use basic indexing to reverse your sorted elevations (or do a web search for how to reverse the order of an array using another NumPy function we haven't covered).
</div>

In [151]:
# add your code here

sorted_elev = np.argsort(station_elev)[::-1]
# sorted_elev = np.flip(np.argsort(station_elev))
t_mon[sorted_elev]

array([[32.87, 33.24, 44.52, 52.6 , 63.07, 77.38, 86.79, 80.6 , 67.25,
        60.35, 45.64, 32.5 ],
       [39.02, 46.58, 53.02, 67.46, 77.7 , 87.05, 91.73, 86.88, 78.14,
        68.03, 52.94, 42.55],
       [37.13, 43.  , 52.34, 61.52, 72.23, 77.02, 83.13, 78.9 , 74.37,
        62.47, 52.82, 38.8 ],
       [21.18, 24.31, 37.95, 50.16, 61.2 , 72.38, 76.71, 76.  , 65.36,
        54.25, 39.67, 30.56],
       [51.87, 57.8 , 65.26, 73.61, 80.79, 86.59, 88.84, 89.54, 81.14,
        75.56, 65.68, 54.3 ],
       [57.68, 61.94, 65.26, 65.59, 74.52, 74.31, 75.95, 77.25, 77.32,
        68.11, 63.24, 59.42],
       [25.85, 29.41, 40.77, 48.34, 61.48, 71.98, 80.74, 73.79, 68.32,
        53.36, 39.11, 31.58],
       [47.39, 53.2 , 52.34, 60.93, 60.49, 66.8 , 68.82, 67.85, 65.02,
        57.91, 52.14, 49.91],
       [32.69, 37.63, 47.02, 52.47, 66.94, 77.12, 78.1 , 77.97, 68.91,
        56.97, 46.16, 35.59],
       [39.49, 44.85, 49.8 , 56.81, 65.21, 74.73, 80.95, 75.09, 69.36,
        60.9 , 50.33

<div class="alert alert-info"> 

## Exercise 10: Using np.where() with Mutliple Array Inputs

Imagine you are working with gridded output from a land surface model (such as the [VIC model](https://vic.readthedocs.io/en/master/Overview/ModelOverview/)). You have the following data on the same grid:

var name | units | description | shape | axes represent
---|---|---|---|---
landfrac | unitless | fraction of each grid cell that is land<br>(1. minus landfrac is grid cell water fraction) | (5,5) | latitude and longitude
t2m | C | 2-meter air temperature | (5,5) | latitude and longitude

<br>

A) Create an array called ```landmask``` of zero's and one's from the array of land fractions below. In your ```landmask``` array, one's should represent grid cells that are mostly land (at least 50%) and zero's should represent grid cells that are mostly water. Print your results.

</div>

In [157]:
landfrac = np.array([[1.,.98,.97,1.,.96],
                     [.92,.97,1.,.96,.98],
                     [.88,.7,.82,.9,1.],
                     [.6,.49,.5,.63,.8],
                     [.12,0.,0.,.25,.3]])

# add your code here
landmask = np.where(landfrac>=.5,1,0)
landmask

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 0, 1, 1, 1],
       [0, 0, 0, 0, 0]])

<div class="alert alert-info"> 

B) Imagine you have a calculation that you want to execute differently based on whether each grid is mostly land or mostly water. Use ```np.where()``` to add 1 degree C to the array ```t2m``` for grids that are mostly water and add 3 degrees C for grids that are mostly land. Save your result as a new variable ```t2m_adj``` and print the result.

In [158]:
t2m = np.array([[26,27,28,29,30],
                [26,27,28,29,30],
                [26,27,28,29,30],
                [26,27,28,29,30],
                [26,27,28,29,30]])

# add your code here

t2m_adj = np.where(landmask==1,t2m+3,t2m+1)
t2m_adj

array([[29, 30, 31, 32, 33],
       [29, 30, 31, 32, 33],
       [29, 30, 31, 32, 33],
       [29, 28, 31, 32, 33],
       [27, 28, 29, 30, 31]])

<div class="alert alert-info"> 

## Exercise 11: Practice Handling NaN

You have the follow 2D array called ```data``` that should contain only float values ranging from -100 to +100. Execute the following data cleaning steps using techniques you've learned in this and previous sections.

A) Programmatically count how many missing values (NaN) are present in the data.

</div>

In [172]:
data = np.array([[1.,2.,np.nan,4.,5.],
                 [-9999.,-999.,3.5,10.7,99.9],
                 [-99.9, np.inf, -60.2,-np.inf,83.3]], dtype=np.float32)

# add your code here

print(np.isnan(data).sum())

1


<div class="alert alert-info"> 

B) Programmatically count how many values in the data are non-finite (NaN and Inf).
</div>

In [173]:
# add your code here

print((~np.isfinite(data)).sum())

3


<div class="alert alert-info"> 
C) Programmatically count how many values are finite but not within the data range -100 to +100. Hint: this will require the use of multiple conditions.
</div>

In [174]:
# add your code here

print(( (np.isfinite(data)) & ((data>100) | (data<-100)) ).sum())
print(np.where( (np.isfinite(data)) & ((data>100) | (data<-100)), 1, 0).sum())

2
2


<div class="alert alert-info"> 
D) Replace all data values that are not within the data range with the missing value ```np.nan```.
</div>

In [175]:
# add your code here

data = np.where((data>100) | (data<-100), np.nan, data)
data

array([[  1. ,   2. ,   nan,   4. ,   5. ],
       [  nan,   nan,   3.5,  10.7,  99.9],
       [-99.9,   nan, -60.2,   nan,  83.3]], dtype=float32)

<div class="alert alert-info"> 
    
E) Select only the finite values and save them to a new variable called ```data_clean```.
</div>

In [176]:
# add your code here

finite = np.where(np.isfinite(data))
data_clean = data[finite]
data_clean

array([  1. ,   2. ,   4. ,   5. ,   3.5,  10.7,  99.9, -99.9, -60.2,
        83.3], dtype=float32)

<div class="alert alert-info"> 
    
F) Fill all NaNs in the ```data``` array with zero.
</div>

In [177]:
# add your code here

data = np.where(np.isnan(data), 0, data)
data

array([[  1. ,   2. ,   0. ,   4. ,   5. ],
       [  0. ,   0. ,   3.5,  10.7,  99.9],
       [-99.9,   0. , -60.2,   0. ,  83.3]], dtype=float32)

<div class="alert alert-info"> 

## Exercise 12: Read and Write NumPy's Native Data Format

A) Create an array called ```arr``` with shape (100,100,100) of random numbers between 0 and 1. Write that array to a file called ```random_numbers.npy```.

</div>

In [197]:
# add your code here

rng = np.random.default_rng()
arr = rng.random((100,100,100))
np.save('random_numbers.npy',arr)

<div class="alert alert-info"> 

B) Read the file you just wrote ```random_numbers.npy``` into an array called ```rand_arr```. Print the shape, min, and max values of ```rand_arr```.

</div>

In [198]:
# add your code here

rand_arr = np.load('random_numbers.npy')
print(rand_arr.shape)
print(rand_arr.min())
print(rand_arr.max())

(100, 100, 100)
2.6597487591262237e-06
0.9999998520108317


<div class="alert alert-info"> 

## Exercise 13: Join and Reshape Data from Multiple Files

There are 30 files named like ```data/pretend/landcover/landcover_yyyy.csv``` for the years 1995 through 2023 containing annual landcover data. Each file contains data for a single year with 10 rows (representing latitudes) and 20 columns (representing longitudes). 

A) Read these files into a 3D array called ```landcover``` with data type int32 and dimensions that represent (time, latitude, longitude) . You'll need to use the glob package, append a list with an array of the contents of each file, and then use the appropriate NumPy function to join your list of arrays together. Print your 3D array shape and data type.  

</div>

In [211]:
# add your code here

file_list = glob.glob('data/pretend/landcover/landcover_*.csv')

array_list = []
for f in file_list:
    array_list.append(np.loadtxt(f,delimiter=',', dtype='int32'))

landcover = np.stack(array_list, axis=0)

print(landcover.shape)
print(landcover.dtype)

(30, 10, 20)
int32


<div class="alert alert-info"> 

B) Reshape your 3D array with dimensions representing (time, latitude, longitude) to a 2D array called ```landcover_2d``` with dimensions representing (time, space). Print the shape of ```landcover_2d```.

</div>

In [212]:
# add your code here

landcover_2d = np.reshape(landcover,(30,-1))
landcover_2d.shape

(30, 200)